Http/routes.php
<?php



Route::group(['middleware' => ['web']], function () {

	Route::group( array("prefix" => "admin", "as"=>"admin."), function() {

    	Route::group(['middleware' => 'auth:dcms'], function() {

    		//GALLERY
    		Route::group( array("prefix" => "gallery"), function() {
    			Route::any('api/table', array('as'=>'gallery.api.table', 'uses' => 'GalleryController@getDatatable'));
    		});
    		Route::resource('gallery','GalleryController');
    });
  });
});



 ?>

Http/Controllers/GalleryController.php
<?php

namespace Dcms\Gallery\Http\Controllers;

use Dcms\Gallery\Models\Gallery;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use View;
use Session;
use Validator;
use Redirect;
use DB;
use DataTables;
use Auth;
use DateTime;
use Config;


class GalleryController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:gallery-browse')->only('index');
        $this->middleware('permission:gallery-add')->only(['create', 'store']);
        $this->middleware('permission:gallery-edit')->only(['edit', 'update']);
        $this->middleware('permission:gallery-delete')->only('destroy');
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        // load the view
        return View::make('dcms::gallery/index');
    }


    public function getDatatable()
    {
        return DataTables::query(DB::connection('project')
            ->table('gallery')
            ->select('id', 'name', 'path')
            ->orderBy('name')
        )
            ->addColumn('edit', function ($model) {
                $edit = '<form method="POST" action="/admin/gallery/' . $model->id . '" accept-charset="UTF-8" class="pull-right"> <input name="_token" type="hidden" value="' . csrf_token() . '"> <input name="_method" type="hidden" value="DELETE">';
                if (Auth::user()->can('gallery-edit')) {
                    $edit .= '<a class="btn btn-xs btn-default" href="/admin/gallery/' . $model->id . '/edit"><i class="far fa-pencil"></i></a>';
                }
                if (Auth::user()->can('gallery-delete')) {
                    $edit .= '<button class="btn btn-xs btn-default" type="submit" value="Delete this article" onclick="if(!confirm(\'Are you sure to delete this item ? \')){return false;};"><i class="far fa-trash-alt"></i></button>';
                }
                $edit .= '</form>';

                return $edit;
            })
            ->rawColumns(['edit'])
            ->make();
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        // load the create form (app/views/articles/create.blade.php)
        return View::make('dcms::gallery/form');
    }

    public function striptopath($givenpath)
    {
        return strrev(substr(strrev($givenpath), strpos(strrev($givenpath), '/')));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(Request $request)
    {
        //$Languages = Language::all();
        $rules = ['name' => 'required', 'path' => 'required'];
        $validator = Validator::make($request->all(), $rules);

        // process the validator
        if ($validator->fails()) {
            return Redirect::to('admin/gallery/create')
                ->withErrors($validator)
                ->withInput();
        } else {
            // store


            $Gallery = new Gallery;

            $Gallery->name = $request->get('name');
            $Gallery->path = $this->striptopath($request->get('path'));

            $Gallery->admin = Auth::guard('dcms')->user()->username;
            $Gallery->save();

            // redirect
            Session::flash('message', 'Successfully created gallery!');

            return Redirect::to('admin/gallery');
        }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        // get the Page
        $Gallery = Gallery::find($id);

        // show the edit form and pass the nerd
        return View::make('dcms::gallery/form')
            ->with('Gallery', $Gallery);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function update(Request $request, $id)
    {
        // validate
        // read more on validation at http://laravel.com/docs/validation
        $rules = ['name' => 'required', 'path' => 'required'];

        $validator = Validator::make($request->all(), $rules);

        // process the login
        if ($validator->fails()) {
            return Redirect::to('admin/gallery/' . $id . '/edit')
                ->withErrors($validator)
                ->withInput();
        } else {
            // store
            $Gallery = Gallery::find($id);

            $Gallery->name = $request->get('name');
            $Gallery->path = $this->striptopath($request->get('path'));

            $Gallery->admin = Auth::guard('dcms')->user()->username;
            $Gallery->save();

            // redirect
            Session::flash('message', 'Successfully updated gallery!');

            return Redirect::to('admin/gallery');
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        // delete
        $Gallery = Gallery::find($id);
        $Gallery->delete();

        // redirect
        Session::flash('message', 'Successfully deleted the gallery!');

        return Redirect::to('admin/gallery');
    }
}

resources/views/gallery/form.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
      <h1>Gallery</h1>
      <ol class="breadcrumb">
        <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
        <li><a href="{!! URL::to('admin/gallery') !!}"><i class="far fa-image"></i> Gallery</a></li>
        @if(isset($Gallery))
            <li class="active">Edit</li>
        @else
            <li class="active">Create</li>
        @endif
      </ol>
    </div>


    <div class="main-content">
    	<div class="row">
				<div class="col-md-12">
					<div class="main-content-block">

              @if(isset($Gallery))
                <h2>Edit gallery</h2>
                {!! Form::model($Gallery, array('route' => array('admin.gallery.update', $Gallery->id), 'method' => 'PUT')) !!}
              @else
                <h2>Create gallery</h2>

                  {!! Form::open(array('url' => 'admin/gallery')) !!}
              @endif

              @if($errors->any())
                <div class="alert alert-danger">{!! Html::ul($errors->all()) !!}</div>
              @endif



              <div class="form-group">
	              {!! Form::label('name', 'Name ') !!}
              	{!! Form::text('name', null, array('class' => 'form-control')) !!}
              </div>

              <div class="form-group">
               {!! Form::label('path', 'Path') !!}

               <div class="input-group">
                   {!! Form::text('path', request()->old('path'), array('class' => 'form-control')) !!}
                 <span class="input-group-btn">
                   {!! Form::button('Browse Server', array('class' => 'btn btn-primary browse-server', 'id'=>'browse_path')) !!}
                 </span>
               </div>
             </div>


							{!! Form::submit('Save', array('class' => 'btn btn-primary')) !!}
              <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>
            	{!! Form::close() !!}

	      	</div>
      	</div>
      </div>
    </div>

<script type="text/javascript" src="{!! asset('/ckeditor/ckeditor.js') !!}"></script>
<script type="text/javascript" src="{!! asset('/ckeditor/adapters/jquery.js') !!}"></script>
<script type="text/javascript" src="{!! asset('/ckfinder/ckfinder.js') !!}"></script>
<script type="text/javascript" src="{!! asset('/ckfinder/ckbrowser.js') !!}"></script>

<script type="text/javascript">
$(document).ready(function() {
	//CKFinder for CKEditor
	CKFinder.setupCKEditor( null, '/ckfinder/' );

	//CKFinder
	$(".browse-server").click(function() {
		BrowseServer( 'Images:/', 'path' );
	})

});

</script>

<script type="text/javascript" src="{!! asset('packages/dcweb/dcms/assets/js/bootstrap.min.js') !!}"></script>
@stop

resources/views/gallery/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Gallery</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li class="active"><i class="far fa-image"></i> Gallery</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    @can('articles-add')
                        <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('/admin/gallery/create') !!}">Create new</a></div>
                    @endcan

                    <h2>Overview</h2>

                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Path</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.gallery.api.table') }}",
                                "columns": [
                                    {data: 'id', name: 'gallery.id'},
                                    {data: 'name', name: 'gallery.name'},
                                    {data: 'path', name: 'gallery.path'},
                                    {data: 'edit', name: 'edit', orderable: false, searchable: false}
                                ]
                            });
                        });
                    </script>

                    <!-- -->


                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

                </div>
            </div>
        </div>
    </div>

@stop